package org.andfRa.mythr.player;

public enum Specifier {

	MELEE_ATTACK_DAMAGE_MODIFIER,
	RANGED_ATTACK_DAMAGE_MODIFIER,
	MAGIC_ATTACK_DAMAGE_MODIFIER,
	CURSE_ATTACK_DAMAGE_MODIFIER,
	BLESSING_ATTACK_DAMAGE_MODIFIER,
	HEALTH_MODIFIER,
	
	MELEE_ATTACK_RATING_MODIFIER,
	RANGED_ATTACK_RATING_MODIFIER,
	MAGIC_ATTACK_RATING_MODIFIER,
	CURSE_ATTACK_RATING_MODIFIER,
	BLESSING_ATTACK_RATING_MODIFIER,
	
	LIGHT_ARMOUR_DEFENCE_RATING_MODIFIER,
	HEAVY_ARMOUR_DEFENCE_RATING_MODIFIER,
	EXOTIC_ARMOUR_DEFENCE_RATING_MODIFIER,
	
}
